### ISSUE TITLE
addPurchaseOrder missing

### ISSUE THREAD

**Issue by Tjab** [picqer/picqer-php#13]
Hi!

Already send an email, and I think I might be unable to create a pull request here (access denied).

Could you add the following to the `Client.php`?

```php
public function addPurchaseorder($params)
{
    return $this->sendRequest('/purchaseorders', $params, self::METHOD_POST);
}
```

**Comment by stephangroen** [comment]
Thanks @Tjab, I have added the code.

You should be able to make a PR to this repository by forking the repo, making the changes and then submitting a PR (via Github).
