### ISSUE TITLE
Method handleRateLimitReached wrong implemented in sendRequest method

### ISSUE THREAD

**Issue by kevinkoenen** [picqer/picqer-php#41]
Hi Picqer,

In the `Client.php` is the method `handleRateLimitReached` wrong implemented.
The local `$headerInfo` variable in the method `sendRequest` will never be updated again after calling `handleRateLimitReached`.

To fix this, you have to return the result of the `handleRateLimitReached` directly instead of saving it to the `$result` variable.

See https://github.com/picqer/picqer-php/blob/main/src/Client.php#L1188C33-L1188C33 for more information.

Instead of 
```php
$result = $this->handleRateLimitReached($endpoint, $params, $method, $filters);
```
Fix:
```php
return $this->handleRateLimitReached($endpoint, $params, $method, $filters);
```

With kind regards,
Kevin Koenen

**Comment by casperbakker** [comment]
Good find @kevinkoenen. We use this ourselves a lot, but never hit this bug. But it definitely was wrong. I now fixed it in the newest release. Thanks!
