### ISSUE TITLE
Create new purchase order

### ISSUE THREAD

**Issue by jasondecode** [picqer/picqer-php#8]
I can't create any purchase orders. When i look at the client.php, i cant find any method for it.

I tried to create my own request:
```php
public function addPurchaseorders($data)
{
     return $this->sendRequest('/purchaseorders', $data, self::METHOD_POST); 
}
```
this will make a post request to:  https://example.picqer.com/api/v1/purchaseorders as it is indicated in the picqer documentation: https://picqer.com/en/api/purchaseorders#h-create-new-purchase-order

But no success, when i pass a warehouse or supplier id that doesn't exists it will return a valid error message but when i send the correct data it will return a HTML string in the error message. 

![picqer issue](https://user-images.githubusercontent.com/31327664/38408812-63ed72e4-397f-11e8-8799-b08b341a6fb6.png)

**Comment by casperbakker** [comment]
That 500 error is totally our mistake, we will fix that.

I see in our exceptions logging that you did not gave an array of products to the `products` key, but only gave an object of 1 product.

If you give an array of products to that key, it should work with your request.

You sent us:
```json
{
  "idsupplier": 333,
  "idwarehouse": 333,
  "products": {
    "idproduct": 333,
    "price": 12,
    "amount": 1
  }
}
```

But it should be like this:

```json
{
  "idsupplier": 333,
  "idwarehouse": 333,
  "products": [
    {
      "idproduct": 333,
      "price": 12,
      "amount": 1
    }
  ]
}
```

**Comment by jasondecode** [comment]
@casperbakker Thanks for your reply! i was kind of confused because of the error message but the problem was just on my side, thanks for correcting me and i really appreciate it!
